jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and browsers
        run: |
          npm install playwright
          npx playwright install

      - name: Run Playwright script for 24f2005754@ds.study.iitm.ac.in
        run: node sumTables.js
